"""
Environment configuration (spec §D, §G). Every rule fails closed: a configuration the service cannot honor
refuses start-up with a plain message. In particular, every option that would need something this build
does not have (a wired token vault, platform app credentials, a perceptual hasher, an age provider, a media
intake store, device/IP identity signals, YouTube id batching) refuses to start rather than pretend.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from fractions import Fraction
from typing import Optional

CALLER_NAMES = ("compliance_38", "creative_production", "onboarding", "clipper_network", "finance_31", "scheduler")
TOKEN_MIN = 32
# SHA-256 of seed/vi_rules_seed.json as generated by devtools/gen_rules_seed.py (pinned in ADR 0007).
PINNED_SEED_SHA256 = "875baeda47d647754042b7a5b61d392ae477a89e19310ef56e1eec26372ab309"
DEFAULT_SEED_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "seed", "vi_rules_seed.json")
PAYABLE_DEFAULT = ("youtube", "tiktok", "instagram")
_REVIEWER_NAME = re.compile(r"[a-z0-9_]{1,40}")


@dataclass
class Settings:
    service_token: str
    caller_tokens: dict = field(default_factory=dict)
    reviewer_tokens: dict = field(default_factory=dict)
    andre_token: Optional[str] = None
    seed_path: str = DEFAULT_SEED_PATH
    seed_sha256: Optional[str] = None
    allow_unpinned_seed: bool = False
    data_dir: Optional[str] = None
    ledger_url: Optional[str] = None
    ledger_token: Optional[str] = None
    reconcile_mode: bool = False
    compliance_url: Optional[str] = None
    compliance_token: Optional[str] = None
    compliance_caller_token: Optional[str] = None
    platforms_enabled: tuple = PAYABLE_DEFAULT
    platform_x_enabled: bool = False
    settle_fetch_grace_h: int = 48
    revision_watch_days: int = 30
    posted_at_tolerance_min: int = 60
    pdq_max_hamming: int = 31
    require_perceptual_match: bool = True
    tt_cover_pdq: bool = False
    fae_buffer_age: int = 25
    minor_purge_hours: int = 24
    anom_velocity_multiple: int = 20
    anom_min_like_rate: Fraction = Fraction(2, 1000)
    anom_ratio_min_views: int = 10_000
    anom_min_avg_view_pct: int = 5
    anom_off_target_share: Fraction = Fraction(1, 2)
    anom_cap_proximity: Fraction = Fraction(2, 100)
    strip_share: Fraction = Fraction(20, 100)
    anom_min_history: int = 5
    yt_derived_signals: bool = False
    feed_youtube_enabled: bool = False
    evidence_retention_days: int = 2557
    liveness_max_gap_days: int = 0
    oembed_enabled: bool = False
    oembed_max_consecutive_days: int = 2
    oembed_max_rps: int = 1
    yt_daily_units: int = 10_000
    yt_reserve_units: int = 1_000
    tt_max_per_min: int = 500
    ig_max_rps: int = 1
    x_monthly_resource_budget: int = 0


def _int(env, name, default, lo, hi) -> int:
    raw = env.get(name)
    if raw in (None, ""):
        return default
    try:
        v = int(raw)
    except ValueError:
        v = lo - 1
    if not lo <= v <= hi:
        raise RuntimeError(f"{name} must be an integer {lo}..{hi}")
    return v


def _frac(env, name, default: Fraction, lo: Fraction, hi: Fraction) -> Fraction:
    raw = env.get(name)
    if raw in (None, ""):
        return default
    if not re.fullmatch(r"[0-9]{1,6}(\.[0-9]{1,6})?", raw.strip()):
        raise RuntimeError(f"{name} must be a plain decimal number")
    v = Fraction(raw.strip())
    if not lo <= v <= hi:
        raise RuntimeError(f"{name} must be within {float(lo)}..{float(hi)}")
    return v


def _flag(env, name, default: bool) -> bool:
    raw = (env.get(name) or "").strip()
    if raw == "":
        return default
    if raw not in ("0", "1"):
        raise RuntimeError(f"{name} must be 0 or 1")
    return raw == "1"


def _tokens(env, name, allowed_names=None) -> dict:
    raw = env.get(name)
    if not raw:
        return {}
    try:
        d = json.loads(raw)
    except ValueError:
        d = None
    if not isinstance(d, dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in d.items()):
        raise RuntimeError(f'{name} must be a JSON object {{"name": "token", ...}}')
    for k, tok in d.items():
        if allowed_names is not None and k not in allowed_names:
            raise RuntimeError(f"{name}: unknown name (allowed: {', '.join(allowed_names)})")
        if allowed_names is None and not _REVIEWER_NAME.fullmatch(k):
            raise RuntimeError(f"{name}: names are 1-40 characters of [a-z0-9_]")
        if len(tok) < TOKEN_MIN or not all(0x21 <= ord(c) <= 0x7e for c in tok):
            raise RuntimeError(f"{name}: the {k} token must be >= {TOKEN_MIN} printable ASCII characters")
    return d


def _off(env, name, what: str) -> None:
    raw = (env.get(name) or "").strip().lower()
    if raw not in ("", "none", "0"):
        raise RuntimeError(f"{name}={raw!r}: {what} is not built in this service; leave it unset (the fail-closed "
                           "stand-in answers 'unavailable')")


def load(env: Optional[dict] = None) -> Settings:
    env = dict(os.environ) if env is None else env
    token = env.get("VI_SERVICE_TOKEN")
    if not token:
        raise RuntimeError("VI_SERVICE_TOKEN is not set. verification-py refuses to start without an auth token "
                           "(fail closed, not open).")
    andre = env.get("VI_ANDRE_APPROVAL_TOKEN") or None
    callers = _tokens(env, "VI_CALLER_TOKENS", CALLER_NAMES)
    reviewers = _tokens(env, "VI_REVIEWER_TOKENS")
    every = list(callers.values()) + list(reviewers.values())
    if len(set(every)) != len(every):
        raise RuntimeError("VI_CALLER_TOKENS / VI_REVIEWER_TOKENS: every token must be distinct")
    if token in every or (andre and andre in every):
        raise RuntimeError("a caller or reviewer token equals the service or Andre token")
    source = (env.get("VI_COUNT_SOURCE") or "owner_oauth_api").strip()
    if source != "owner_oauth_api":
        raise RuntimeError("VI_COUNT_SOURCE accepts only owner_oauth_api (spec D1: official API via the clipper's own "
                           "OAuth connection; no scraping)")
    raw_pl = env.get("VI_PLATFORMS_ENABLED")
    platforms = PAYABLE_DEFAULT if raw_pl in (None, "") else tuple(p.strip() for p in raw_pl.split(",") if p.strip())
    for p in platforms:
        if p not in PAYABLE_DEFAULT:
            raise RuntimeError(f"VI_PLATFORMS_ENABLED: {p!r} is not accepted (youtube, tiktok, instagram; X only via "
                               "VI_PLATFORM_X_ENABLED; Snapchat and Twitch are never payable)")
    for name, what in (("VI_VAULT", "a token vault adapter (Cybersecurity 22)"),
                       ("VI_HASHER", "a perceptual-hash provider"), ("VI_AGE_PROVIDER", "an age-assurance provider"),
                       ("VI_MEDIA_INTAKE", "a media intake store")):
        _off(env, name, what)
    for p in ("YOUTUBE", "TIKTOK", "INSTAGRAM", "X"):
        if env.get(f"VI_{p}_APP_CREDENTIALS_REF"):
            raise RuntimeError(f"VI_{p}_APP_CREDENTIALS_REF is set but no token vault is wired (VI_VAULT): the real "
                               "platform adapters run only with both; refusing to start")
    if _flag(env, "VI_DEVICE_SIGNALS_ENABLED", False):
        raise RuntimeError("VI_DEVICE_SIGNALS_ENABLED=1: device/IP identity signals are not built (VI-CQ-04, Legal 37 "
                           "privacy notice pending); refusing to start")
    if _int(env, "VI_YT_IDS_PER_CALL", 1, 1, 50) != 1:
        raise RuntimeError("VI_YT_IDS_PER_CALL: only 1 is supported (id batching is UNVERIFIED in the research)")
    unpinned = _flag(env, "VI_ALLOW_UNPINNED_SEED", False)
    seed_sha = env.get("VI_SEED_SHA256") or None
    if seed_sha is not None and seed_sha != PINNED_SEED_SHA256 and not unpinned:
        raise RuntimeError("VI_SEED_SHA256 differs from the pinned seed hash; refusing to start "
                           "(set VI_ALLOW_UNPINNED_SEED=1 for a NON-PRODUCTION run)")
    if unpinned and seed_sha is None:
        raise RuntimeError("VI_ALLOW_UNPINNED_SEED=1 needs VI_SEED_SHA256 (the unpinned seed's own hash, stated)")
    comp = [env.get(k) or None for k in ("VI_COMPLIANCE_URL", "VI_COMPLIANCE_TOKEN", "VI_COMPLIANCE_CALLER_TOKEN")]
    if any(comp) and not all(comp):
        raise RuntimeError("VI_COMPLIANCE_URL, VI_COMPLIANCE_TOKEN and VI_COMPLIANCE_CALLER_TOKEN must be set together "
                           "(or none: the fail-closed Compliance stand-in)")
    yt_units = _int(env, "VI_YT_DAILY_UNITS", 10_000, 1, 10_000_000)
    yt_reserve = _int(env, "VI_YT_RESERVE_UNITS", 1_000, 0, 10_000_000)
    if yt_reserve >= yt_units:
        raise RuntimeError("VI_YT_RESERVE_UNITS must be below VI_YT_DAILY_UNITS")
    return Settings(
        service_token=token, caller_tokens=callers, reviewer_tokens=reviewers, andre_token=andre,
        seed_path=env.get("VI_SEED_PATH") or DEFAULT_SEED_PATH, seed_sha256=seed_sha, allow_unpinned_seed=unpinned,
        data_dir=env.get("VI_DATA_DIR") or None,
        ledger_url=env.get("LEDGER_SERVICE_URL") or None, ledger_token=env.get("LEDGER_SERVICE_TOKEN") or None,
        reconcile_mode=_flag(env, "VI_RECONCILE_MODE", False),
        compliance_url=comp[0], compliance_token=comp[1], compliance_caller_token=comp[2],
        platforms_enabled=platforms, platform_x_enabled=_flag(env, "VI_PLATFORM_X_ENABLED", False),
        settle_fetch_grace_h=_int(env, "VI_SETTLE_FETCH_GRACE_H", 48, 1, 168),
        revision_watch_days=_int(env, "VI_REVISION_WATCH_DAYS", 30, 1, 365),
        posted_at_tolerance_min=_int(env, "VI_POSTED_AT_TOLERANCE_MIN", 60, 0, 1440),
        pdq_max_hamming=_int(env, "VI_PDQ_MAX_HAMMING", 31, 0, 256),
        require_perceptual_match=_flag(env, "VI_REQUIRE_PERCEPTUAL_MATCH", True),
        tt_cover_pdq=_flag(env, "VI_TT_COVER_PDQ", False),
        fae_buffer_age=_int(env, "VI_FAE_BUFFER_AGE", 25, 18, 40),
        minor_purge_hours=_int(env, "VI_MINOR_PURGE_HOURS", 24, 1, 24),
        anom_velocity_multiple=_int(env, "VI_ANOM_VELOCITY_MULTIPLE", 20, 1, 1000),
        anom_min_like_rate=_frac(env, "VI_ANOM_MIN_LIKE_RATE", Fraction(2, 1000), Fraction(0), Fraction(1)),
        anom_ratio_min_views=_int(env, "VI_ANOM_RATIO_MIN_VIEWS", 10_000, 0, 10**12),
        anom_min_avg_view_pct=_int(env, "VI_ANOM_MIN_AVG_VIEW_PCT", 5, 0, 100),
        anom_off_target_share=_frac(env, "VI_ANOM_OFF_TARGET_SHARE", Fraction(1, 2), Fraction(0), Fraction(1)),
        anom_cap_proximity=_frac(env, "VI_ANOM_CAP_PROXIMITY", Fraction(2, 100), Fraction(0), Fraction(1)),
        strip_share=_frac(env, "VI_STRIP_SHARE", Fraction(20, 100), Fraction(1, 100), Fraction(1)),
        anom_min_history=_int(env, "VI_ANOM_MIN_HISTORY", 5, 1, 1000),
        yt_derived_signals=_flag(env, "VI_YT_DERIVED_SIGNALS", False),
        feed_youtube_enabled=_flag(env, "VI_FEED_YOUTUBE_ENABLED", False),
        evidence_retention_days=_int(env, "VI_EVIDENCE_RETENTION_DAYS", 2557, 1, 36500),
        liveness_max_gap_days=_int(env, "VI_LIVENESS_MAX_GAP_DAYS", 0, 0, 7),
        oembed_enabled=_flag(env, "VI_OEMBED_ENABLED", False),
        oembed_max_consecutive_days=_int(env, "VI_OEMBED_MAX_CONSECUTIVE_DAYS", 2, 0, 7),
        oembed_max_rps=_int(env, "VI_OEMBED_MAX_RPS", 1, 1, 10),
        yt_daily_units=yt_units, yt_reserve_units=yt_reserve,
        tt_max_per_min=_int(env, "VI_TT_MAX_PER_MIN", 500, 1, 599),
        ig_max_rps=_int(env, "VI_IG_MAX_RPS", 1, 1, 100),
        x_monthly_resource_budget=_int(env, "VI_X_MONTHLY_RESOURCE_BUDGET", 0, 0, 3_000_000),
    )
