# AEGIS round 8 corpus, VERBATIM from review8/probes/corpus8.py (fix wave 9 FP guard).
# AEGIS round 8 — FRESH corpus, written for this round (none reused from corpus6/corpus7/my_captions).
# Three strata: plain captions across niches, emoji-heavy captions, and creator slang / abbreviations
# (vowel-less tokens: the stacked two-of-three rule's natural FP surface). None says a never-say phrase.
NEVER_SAY_A = [  # the round-7 list (so results are comparable)
    "guaranteed returns", "get rich", "make money", "risk free", "double your money", "no risk",
    "miracle cure", "passive income", "financial freedom", "overnight success", "lose weight fast",
    "clinically proven", "doctor recommended", "free money", "get rich quick", "cure",
]
NEVER_SAY_B = [  # a fresh list, never seen by the implementer
    "instant approval", "zero fees", "debt free", "burn fat", "anti aging", "no side effects",
    "quit your job", "easy money", "cash back guaranteed", "melt belly fat", "reverse aging", "beat the market",
]

PLAIN = [
    "Hand-thrown mugs, glazed in small runs. Each one is a little different",
    "Our sourdough starter is eleven years old and still bossy",
    "Road test: the commuter bike did 40 km in the rain and came home clean",
    "Fresh basil, cracked pepper, a squeeze of lemon. Dinner in twelve minutes",
    "New studio hours: Tuesday to Sunday, closed Mondays for deep cleaning",
    "We planted 300 trees with the spring order volume. Thank you",
    "The desk lamp now dims to 1 percent for late reading",
    "Stitched by hand in Oaxaca, dyed with cochineal",
    "The backpack survived a year of daily use. Here is the wear report",
    "Bring your own jar and get the refill at cost",
    "Pottery class seats open at noon, eight per session",
    "Candles poured with coconut wax, wicks trimmed for a clean burn",
    "Our tacos use tortillas pressed the same morning",
    "Swipe for the before and after of the kitchen refit",
    "The trail shoes have a new outsole with deeper lugs",
    "We tested five blenders so you do not have to",
    "Every order ships in recycled cardboard, no plastic fill",
    "The book club pick this month is a slim novel about lighthouse keepers",
    "Tuning tip: loosen the strings before a long flight",
    "Houseplant care 101: water less than you think",
    "The pantry staples bundle has lentils, rice, oats and chickpeas",
    "Meet Rosa, who has run our night shift bakery for nine years",
    "Weekend market stall: find us under the green awning",
    "Our dog beds come apart for washing. Yes, the whole thing",
    "Knife sharpening service is back on Thursdays",
    "Behind the scenes of a product photo shoot with one lamp and a bedsheet",
    "Fermented hot sauce, aged 90 days in oak",
    "The linen duvet softens with every wash",
    "Kids eat free on Sundays with any adult main",
    "Gym tip: film your squat from the side and check your depth",
    "The notebook paper takes fountain pen ink without bleeding",
    "Frame shop update: museum glass is now standard",
    "Travel mug keeps coffee hot for six hours, tested on a ferry",
    "We rebuilt the checkout so it takes two taps",
    "Local honey from hives on the library roof",
    "Your questions about compost, answered by our gardener",
    "The jacket packs into its own pocket",
    "Summer menu: peach salad, grilled corn, lime granita",
    "Bike fitting appointments available all week",
    "Weaving workshop recap: forty people, one very tangled loom",
    "Here is how we calculate shipping, line by line",
    "Tea tasting flight: four greens from four gardens",
    "The ceramic planter has a drainage hole and a saucer",
    "Our returns team replies within a day, usually faster",
    "Loaf of the week: rye with caraway and molasses",
    "Soft launch of the dog treat line. Taste testers wanted",
    "The yoga mat is 5 mm thick and does not slip when wet",
    "Studio playlist is up. Mostly jazz, some regret",
    "We switched suppliers to get organic cotton thread",
    "Nail art set: twelve colours, one top coat",
    "The camping stove boils a litre in three minutes",
    "Grandma's lemon cake recipe, finally written down",
    "Charity bake sale raised enough for two new benches",
    "Beard oil with cedar and orange, no synthetic scent",
    "Winter tyres fitted while you wait",
    "The newsletter is monthly and short. Promise",
    "Three ways to style a scarf in under a minute",
    "Budget tip: plan meals around what is already in the fridge",
    "Saving for a trip? Here is the spreadsheet we use",
    "Our accountant explains receipts for freelancers in plain words",
    "Interest rates changed this week. Here is what that means for renters",
    "The pension talk at the library is free and open to all",
    "Doctor visits are easier with a written list of questions",
    "Our nurse practitioner answers skin questions every Friday",
    "Stretching routine for desk workers, ten minutes",
    "Protein oats: oats, milk, a scoop of yoghurt, berries",
    "Walking club meets at 7 by the fountain",
    "Sleep hygiene basics: dark room, cool temperature, no phone",
    "The cycling class is beginner friendly, bring water",
    "Clinic hours extended for flu season",
    "Pharmacy tip: ask about generic versions",
    "Our trainer explains progressive overload with a stack of books",
    "Market update: the farmers stall has early strawberries",
    "Rich chocolate tart with a thin salted crust",
    "Money-saving swap: brew your coffee at home twice a week",
    "Make ahead lunches for the whole week in one hour",
    "Getting ready for the festival: our packing list",
    "Free parking behind the shop after five",
    "No reservations needed on weekday lunches",
    "Returns are free within 30 days",
    "Double chocolate cookies are back by popular demand",
    "Weight of the new tent: 1.4 kg with poles",
    "Fast shipping to most of the country, two days",
    "Proven recipe: the same brownie since 1998",
    "Overnight oats with cinnamon and apple",
    "Passive house design keeps the studio warm without a boiler",
    "Freedom to choose: every plan cancels anytime",
    "Recommended by our regulars: the mushroom toast",
    "Returns portal is down for maintenance until 3 pm",
    "Our financial year ends in March; invoices by the 20th please",
]
EMOJI = [
    "Fresh 🍓 tarts on the counter till we sell out",
    "Morning ☕ and a quiet shop. Come say hi",
    "New 🧶 colours just landed",
    "Beach day 🏖️ essentials in one tote",
    "Pizza 🍕 Friday is back, 5 to 9",
    "Our 🐶 of the month is Biscuit",
    "Rainy day 🌧️ reading list below",
    "Birthday 🎂 cakes need 48 hours notice",
    "Plant sale 🌿 this Saturday only",
    "Game night 🎲 every Thursday",
    "Road trip 🚗 playlist is live",
    "Holiday 🎄 hours posted in stories",
    "Gift cards 🎁 never expire",
    "Tacos 🌮 and tunes on the patio",
    "Ice cream 🍦 flavour vote closes tonight",
    "Workshop ✂️ seats are limited",
    "Sale ends at midnight ⏰",
    "Hot 🔥 new arrivals in the denim section",
    "Save 💰 with the bundle, details in bio",
    "Pay 💳 in store or online",
    "Five ⭐ from our last hundred reviews",
    "Thank you 🙏 for 10k",
    "Order by Friday 📦 for weekend delivery",
    "Win 🏆 a year of coffee, rules in bio",
    "Trail run 🏃 club meets at dawn",
    "Sleep 😴 better with the linen sheets",
    "Big 📈 week for the bakery, thank you all",
    "Gym 💪 open 24/7 for members",
    "Quick ⚡ tip: descale the kettle monthly",
    "The 💎 of our collection: the emerald ring",
    "Launch 🚀 day for the new app",
    "Lab 🔬 tested sunscreen, SPF 30",
    "Guaranteed ✅ delivery before Christmas if you order by the 18th",
    "Pricing 💲 is on the website",
    "We 💚 our customers",
    "Coffee ☕ + croissant 🥐 = $6",
    "Only $20 💵 for the starter kit",
    "Price drop 📉 on last season's jackets",
    "Night 🌙 market this Friday",
    "Doctor 🩺 appointments online now",
]
SLANG = [
    "grwm for the gala rn, fit chk at the end",
    "ngl this cardigan slaps",
    "pls dm for wholesale rates",
    "tbh the brown shade is my fav",
    "lmk ur fav flavour below",
    "dbl tap if u agree",
    "rsvp by fri, spots r limited",
    "new drop rn, link in bio",
    "mfw the oven timer goes off",
    "brb restocking the shelves",
    "srsly the best brunch in town",
    "hrs: mon-fri 9-5, sat 10-2",
    "w/ free gift wrap thru dec",
    "pkg ships 2mrw, tysm for ur order",
    "ootd: thrifted blazer + mom jeans",
    "fyi the market is cash only this wk",
    "smth new is coming, stay tuned",
    "tmrw we open at 8 not 9",
    "gm to everyone except the printer",
    "idk who needs to hear this but hydrate",
    "nvm the rain, we r still open",
    "bts of our shoot w/ the new lens",
    "irl the colour is even better",
    "pov: u finally found ur size",
    "mk sure u check the size chart",
    "gt ready w me for date night",
    "rly proud of this batch",
    "thx for 5k, giveaway soon",
    "dm me ur questions abt refunds",
    "yr in review: 12 mths, 400 orders",
    "my fave rn is the matcha",
    "grl dinner: bread, cheese, wine",
    "sm pls, the small size is back",
    "wknd sale on all mugs",
    "pls rt to help a small biz",
    "fr the comfiest socks we make",
    "nm just packing orders",
    "hbd to our head baker",
    "wfh setup tour, desk + lamp",
    "stk up on candles before the holidays",
]
CAPTIONS = PLAIN + EMOJI + SLANG
