"""
Ordinary captions for the never-say false-positive measurement (fix wave 5,
NEW-1). Realistic, varied, marketing-style English of the kind clippers and
brand accounts post: personal finance, fitness, food, beauty, tech, travel,
e-commerce, podcasts, creators. Written to be ordinary — NOT filtered to
avoid words near the never-say list (they deliberately include everyday
words such as "make more", "get rid of", "no rush", "rich flavour",
"guaranteed fit", "money-back", "return policy", "free shipping").

None of them says a never-say phrase from NEVER_SAY_FP_LIST.
"""

# A realistic never-say list for a finance / wellness creator campaign.
NEVER_SAY_FP_LIST = [
    "guaranteed returns", "get rich", "make money", "risk free", "double your money", "no risk",
    "miracle cure", "passive income", "financial freedom", "overnight success", "lose weight fast",
    "clinically proven", "doctor recommended", "free money", "get rich quick", "cure",
]

CAPTIONS = [
    # personal finance / budgeting
    "The budget myth nobody talks about #ad",
    "Three money habits I wish I'd started at 22",
    "How I cut my grocery bill in half without couponing",
    "Stop paying for subscriptions you forgot about",
    "My simple rule for splitting rent with roommates",
    "Why your emergency fund should live in a separate account",
    "Make more room in your budget by tracking one category",
    "Get rid of the guilt around spending on things you love",
    "No rush — build the habit first, the numbers follow",
    "Here's what a realistic first budget looks like",
    "Paying off my car loan early: was it worth it?",
    "The 50/30/20 rule, explained in under a minute",
    "What I spend in a week living in Chicago",
    "Your credit score isn't a moral grade",
    "Five questions to ask before you sign a lease",
    "Saving for a wedding without losing your mind",
    "I tried a no-spend month. Here's what happened.",
    "Retirement accounts, explained like you're busy",
    "Money talks are awkward. Do them anyway.",
    "Budgeting apps I actually kept using",
    "How to negotiate your salary without sounding pushy",
    "Rich people don't budget? Not true.",
    "Your first paycheck: where should it go?",
    "Index funds vs picking stocks, the honest version",
    "Investing involves risk. Here's how to think about it.",
    "Don't panic-sell when the market dips",
    "My bank charged me a fee and I got it back",
    "Side hustle ideas that don't need a big audience",
    "Taxes for freelancers: set aside a slice of every invoice",
    "Why I stopped chasing the perfect spreadsheet",
    "Cash envelopes are back and honestly they work",
    "What financial advisors wish you knew",
    "Before you buy a house, read this",
    "Student loans: the payoff plan that fit my life",
    "A calm, boring money plan beats an exciting one",
    "Get your receipts in order before tax season",
    "Weekly money check-in: fifteen minutes, every Sunday",
    "The real cost of owning a dog in the city",
    "How I plan for irregular income months",
    "Returns on savings accounts went up — check yours",
    # fitness / wellness
    "Leg day doesn't have to take two hours",
    "A ten-minute mobility routine for desk workers",
    "Protein oats that actually taste good",
    "Why rest days make you stronger",
    "My go-to warm-up before every run",
    "Walking counts. Seriously.",
    "How I got back into lifting after a year off",
    "Form check: the hip hinge, slowed down",
    "Stretch with me before bed",
    "Hydration tips for hot summer runs",
    "Beginner-friendly core workout, no equipment",
    "What I eat in a day as a marathon trainee",
    "Sleep is the most underrated recovery tool",
    "Strength training for women over forty",
    "The treadmill incline walk everyone's talking about",
    "Five exercises for stronger knees",
    "Yoga flow for tight hips",
    "Post-workout snacks under 200 calories",
    "Progress, not perfection — month three update",
    "How to pick running shoes that fit",
    "Our coaches build plans around your schedule",
    "Recovery smoothie with frozen berries and spinach",
    "Try this breathing exercise when you feel stressed",
    "A gentle routine for sore muscles",
    "Consistency beats intensity every time",
    # food / cooking
    "One-pan lemon chicken for busy weeknights",
    "This rich, creamy tomato soup takes 20 minutes",
    "Sourdough discard pancakes, fluffy every time",
    "Meal prep for the week in under an hour",
    "The secret to crispy roast potatoes",
    "Homemade pizza dough, no mixer needed",
    "Rich chocolate brownies with a crackly top",
    "Five pantry staples I always keep stocked",
    "Easy vegetarian tacos the whole family loves",
    "How to make restaurant-style fried rice at home",
    "Cold brew at home: cheaper and better",
    "A salad that actually keeps you full",
    "Banana bread, but make it healthier",
    "Street food tour through Mexico City",
    "Knife skills every home cook should know",
    "Slow cooker chili for game day",
    "Better than takeout: sesame noodles",
    "Summer peach cobbler with a buttery crust",
    "What I cook when the fridge is almost empty",
    "Our spice blend brings rich flavour to any dish",
    "Soft scrambled eggs, the French way",
    "Freezer-friendly soups for winter",
    "Brunch board ideas for your next get-together",
    "How to season a cast iron pan properly",
    "Five-minute garlic butter shrimp",
    # beauty / fashion
    "My five-minute morning skincare routine",
    "Fall outfit ideas with pieces you already own",
    "The only sunscreen that doesn't leave a white cast",
    "Get ready with me for a wedding",
    "Curly hair wash day, start to finish",
    "Capsule wardrobe for a week in Paris",
    "Drugstore dupes for high-end lipsticks",
    "Nail art you can do with a toothpick",
    "Guaranteed fit or free exchanges on every order",
    "How to style white sneakers five ways",
    "Our new serum is fragrance-free and gentle",
    "Hair oil that tamed my frizz",
    "Thrift haul: vintage denim finds",
    "Makeup for hooded eyes, step by step",
    "A minimalist jewelry stack I wear daily",
    "Winter coat try-on haul",
    "Dermatologist tips for dry winter skin",
    "Color analysis changed how I shop",
    "Easy updos for second-day hair",
    "Our return policy: 30 days, no questions asked",
    # tech / gadgets / apps
    "Five phone settings you should change today",
    "Unboxing the new noise-cancelling headphones",
    "My desk setup for working from home",
    "How to back up your photos without paying extra",
    "This keyboard shortcut saves me an hour a week",
    "Smart home gadgets that are actually useful",
    "Laptop buying guide for students",
    "Is the new tablet worth the upgrade?",
    "Password managers, explained simply",
    "Tiny productivity app I use every day",
    "Battery tips that really help your phone last longer",
    "Our app now syncs across all your devices",
    "Setting up a home network the right way",
    "Why I switched to a mechanical keyboard",
    "Camera settings for crisp night photos",
    "Five browser extensions I can't live without",
    "Cleaning your laptop fan in ten minutes",
    "The best budget earbuds this year",
    "Turn off these notifications for more focus",
    "How to spot a phishing email",
    # travel
    "Three days in Lisbon on a budget",
    "Packing list for a carry-on only trip",
    "Hidden beaches near Split, Croatia",
    "How I find cheap flights without hacks",
    "Road trip through Utah's national parks",
    "Tokyo food guide for first-timers",
    "The best time of year to visit Iceland",
    "Travel insurance: do you really need it?",
    "A slow weekend in the Scottish Highlands",
    "Train travel across Italy, step by step",
    "What to know before renting a car abroad",
    "Budget hostels that feel like boutique hotels",
    "Sunrise hike worth waking up for",
    "Airport lounge access without a fancy card",
    "Our tours are small-group and locally guided",
    # e-commerce / brand
    "Free shipping on orders over $50 this week #ad",
    "New drop: linen shirts in five colors",
    "Money-back guarantee if it doesn't fit your routine",
    "Limited edition candles are back in stock",
    "Handmade ceramics from our studio in Portland",
    "Meet the team behind our small business",
    "Behind the scenes of our photo shoot",
    "Customer review of the week: thank you, Dana!",
    "Gift guide for people who have everything",
    "We plant a tree for every order",
    "Use code FALL15 for 15% off",
    "Back in stock: the tote everyone asked for",
    "Our packaging is now plastic-free",
    "Holiday hours and shipping deadlines",
    "How our coffee goes from farm to cup",
    "Bundle and save on the starter kit",
    "Restocking the bestsellers this Friday",
    "Tag us in your photos for a chance to be featured",
    "Our founder's story, in her own words",
    "Pre-orders open now for the winter collection",
    # podcasts / creators / education
    "New episode: the psychology of spending",
    "Listen on Pod Plus — link in bio",
    "Full interview out now on our channel",
    "This guest changed how I think about work",
    "Clip from this week's episode #ad",
    "Ask me anything about starting a podcast",
    "Study with me: two-hour pomodoro session",
    "How I edit videos on my phone",
    "Reading list for the fall",
    "Book review: a thriller I couldn't put down",
    "Learn Spanish with me — day 30",
    "The history of the humble paperclip",
    "Three lessons from my first year freelancing",
    "How I plan a month of content in one afternoon",
    "Answering your questions about burnout",
    "Why I make videos about money every week",
    "Tips for public speaking when you're nervous",
    "A day in the life of a nurse on night shift",
    "What teaching kindergarten taught me",
    "My writing routine, honestly",
    # home / family / pets / misc
    "Small apartment storage ideas that work",
    "DIY shelf install in under an hour",
    "Toddler-friendly dinner ideas",
    "How we split chores as a couple",
    "Plant care for people who forget to water",
    "Our rescue dog's first week home",
    "Organizing the junk drawer, finally",
    "Cozy reading nook makeover",
    "Weekend garden update: tomatoes everywhere",
    "Budget-friendly birthday party ideas",
    "How to clean grout without harsh chemicals",
    "Back-to-school routine for busy mornings",
    "Cat toys that are actually worth buying",
    "Renter-friendly kitchen upgrades",
    "A calmer bedtime routine for kids",
    "First apartment essentials checklist",
    "Painting our front door a bold color",
    "The laundry hack my grandmother swore by",
    "How we saved on our energy bill this winter",
    "Moving checklist so nothing gets lost",
    # extra variety
    "Watch till the end for the best part",
    "Part two is up now",
    "Duet this with your own tips",
    "Save this for later",
    "Tell me your favorite in the comments",
    "Which one would you pick?",
    "We tested five blenders so you don't have to",
    "Honest review after six months of use",
    "Is it worth the hype? Let's find out.",
    "This changed my morning routine completely",
    "Link in bio for the full recipe",
    "Swipe for before and after",
    "Quick tip for smoother mornings",
    "Everything I got done before 9am",
    "Road to my first half marathon",
    "Making money moves one small step at a time",
    "Make memories, not clutter",
    "Pan sauce in five minutes, rich and glossy",
    "No risky shortcuts, just steady progress",
    "Beat the Sunday scaries: plan Monday on Friday",
    "Freedom to travel starts with a plan",
    "Financial literacy should be taught in schools",
    "Passive voice is killing your resume",
    "Doctor's appointments are easier when you bring notes",
    "Clinical trials, explained by a researcher",
    "Double your veggies with this sneaky sauce",
    "Lose the clutter, keep what you love",
    "Weight training myths, busted",
    "Overnight oats five ways",
    "Success looks different for everyone",
    "Free museum days in your city",
    "Guaranteed to make you smile",
    "Returns are free within 30 days",
    "Make your money last until payday",
]
