"""The closed catalogue of reason codes Sales answers with. An error body carries one of these and nothing from the
request (no email, no phone, no name, no text). ``R(code)`` refuses a code not listed here."""

from __future__ import annotations

CODES = frozenset({
    # callers and Andre
    "CALLER_UNKNOWN", "CALLER_NOT_ALLOWED", "ANDRE_APPROVAL_REQUIRED", "ANDRE_APPROVAL_INVALID",
    "ANDRE_TOKEN_NOT_CONFIGURED",
    # leads and pipeline
    "SOURCE_NOT_ALLOWED", "SOURCE_NOT_WIRED", "REFERRER_REQUIRED", "REFERRER_NOT_ALLOWED", "BRAND_PRODUCT_MISMATCH",
    "EMAIL_INVALID", "PHONE_INVALID", "DOMAIN_INVALID", "CONTACT_CHANNEL_REQUIRED", "TIME_ZONE_INVALID",
    "FORBIDDEN_FIELD", "LEAD_NOT_FOUND", "LEAD_CLOSED", "LEAD_NOT_QUALIFIED", "LEAD_UNROUTED", "CONTACT_NOT_FOUND",
    "OPPORTUNITY_NOT_FOUND", "OPPORTUNITY_CLOSED", "TARGET_NOT_FOUND", "TASK_NOT_FOUND", "TASK_CLOSED",
    # consent, suppression, outreach
    "CONTACT_NO_EMAIL", "CONTACT_NO_PHONE", "CONSENT_REQUIRED", "CONSENT_IN_FUTURE", "SUPPRESSED",
    "TIME_ZONE_UNKNOWN", "QUIET_HOURS", "OUTREACH_NOT_CONFIGURED", "UNSUBSCRIBE_TOKEN_UNKNOWN",
    "REPLY_SENDER_REQUIRED", "MESSAGE_NOT_FOUND", "MESSAGE_NOT_QUEUED", "MESSAGE_NOT_SENT",
    # templates
    "TEMPLATE_NOT_FOUND", "TEMPLATE_EXISTS", "TEMPLATE_NOT_APPROVED", "TEMPLATE_HASH_MISMATCH",
    "TEMPLATE_ALREADY_APPROVED", "SUBJECT_REQUIRED", "SUBJECT_DECEPTIVE", "PLACEHOLDER_UNKNOWN", "SMS_TOO_LONG",
    # price books and proposals
    "LINE_UNKNOWN", "LINE_REPEATED", "PRICE_NOT_APPROVED", "PRICE_VERSION_STALE", "PRICE_REQUIRED", "MARKUP_REQUIRED",
    "PRICE_CHANGED", "MONEY_INVALID", "MEDIA_COST_REQUIRED", "MEDIA_FIELDS_ON_SERVICE_LINE", "QUANTITY_INVALID",
    "NO_LINES", "DISCOUNT_TOO_LARGE", "PROPOSAL_NOT_FOUND", "PROPOSAL_NOT_PENDING", "PROPOSAL_NOT_APPROVED",
    "PROPOSAL_NOT_SENT", "PROPOSAL_CLOSED", "PROPOSAL_EXPIRED", "PROPOSAL_HASH_MISMATCH", "LEGAL_UNAVAILABLE",
    "CONTRACT_NOT_IN_FORCE",
    # generic
    "REQUEST_ID_REUSED", "LEDGER_UNAVAILABLE", "STORE_UNAVAILABLE", "INTEGRITY_UNVERIFIED", "JOB_UNKNOWN", "INVALID",
})


def R(code: str) -> str:
    if code not in CODES:
        raise AssertionError(f"reason code not in the catalogue: {code}")
    return code
