"""
Environment configuration (Legal spec §E, §H). Every rule fails closed: a configuration the service cannot
honor refuses start-up with a plain message. Options that would need something this build does not have (a
counsel channel, an e-sign provider, portal FAQ answers) refuse to start rather than pretend.

Seed pinning (spec §B.12, G4): every file in ``seed/`` is pinned by SHA-256 here and in ADR 0010. The rules
seed alone may run unpinned for a NON-PRODUCTION run (``LEGAL_ALLOW_UNPINNED_SEED=1`` with its own hash stated
in ``LEGAL_SEED_SHA256``; /health then says ``rules_pinned: false``) — the N14-13 override. Any other seed
file that differs refuses start-up with no override.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Optional

CALLER_NAMES = ("compliance_38", "clipper_network", "verification_integrity", "creative_production", "onboarding",
                "finance_31", "hub", "esign_gateway", "scheduler")
TOKEN_MIN = 32
SEED_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "seed")
RULES_SEED = "legal_rules_seed.json"
# SHA-256 of each seed file as generated by devtools/gen_seeds.py (pinned in ADR 0010).
PINNED_SEEDS = {
    "legal_rules_seed.json": "cebb5b1418eee245a472d040bfd8795ce3d93338902c4939b0454655f90afe9b",
    "documents.json": "c4819ab8017e4d563a776b0e57964ff821b69f000ec5189581be858fb933f823",
    "counsel_questions.json": "8a00b2912611547fe7d38c3f9d3794824df804168aa2673cd1532cb666da2778",
    "retention.json": "712efb7a7ed72bdd5896c47f51f9f1cd9fcc7503383ced80568b1385d80ae286",
    "signoff_topics.json": "3651fc599248be8656e83fcffc9c5b66d48a0d9712437c316f6678c95a9ab590",
    "advice_patterns.json": "cf43405ee79ac0779ac466605b31e7ea6e61fa9ba9a7af1ca3e7a440a1719be3",
    "us_federal_holidays.json": "54cf0db79fa3c4f9eb452797681d8c7114bd57aa43557896a76eaaada8b1b1f5",
}
PINNED_SEED_SHA256 = PINNED_SEEDS[RULES_SEED]
_MONEY = re.compile(r"^(0|[1-9][0-9]*)\.[0-9]{2}$")


@dataclass
class Settings:
    service_token: str
    caller_tokens: dict = field(default_factory=dict)
    andre_token: Optional[str] = None
    seed_dir: str = SEED_DIR
    seed_sha256: Optional[str] = None
    allow_unpinned_seed: bool = False
    data_dir: Optional[str] = None
    ledger_url: Optional[str] = None
    ledger_token: Optional[str] = None
    reconcile_mode: bool = False
    compliance_url: Optional[str] = None
    compliance_token: Optional[str] = None
    compliance_caller_token: Optional[str] = None
    agent_max_fallback: int = 1
    dispute_threshold: Decimal = Decimal("5000.00")
    memo_review_days: int = 90
    hold_renotice_days: int = 90
    filing_alert_days: int = 60
    esign_consent_required: bool = True
    business_tz: str = "America/Los_Angeles"


def _int(env, name, default, lo, hi) -> int:
    raw = env.get(name)
    if raw in (None, ""):
        return default
    try:
        v = int(raw)
    except ValueError:
        v = lo - 1
    if not lo <= v <= hi:
        raise RuntimeError(f"{name} must be an integer {lo}..{hi}")
    return v


def _flag(env, name, default: bool) -> bool:
    raw = (env.get(name) or "").strip()
    if raw == "":
        return default
    if raw not in ("0", "1"):
        raise RuntimeError(f"{name} must be 0 or 1")
    return raw == "1"


def _tokens(env, name) -> dict:
    raw = env.get(name)
    if not raw:
        return {}
    try:
        d = json.loads(raw)
    except ValueError:
        d = None
    if not isinstance(d, dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in d.items()):
        raise RuntimeError(f'{name} must be a JSON object {{"name": "token", ...}}')
    for k, tok in d.items():
        if k not in CALLER_NAMES:
            raise RuntimeError(f"{name}: unknown name (allowed: {', '.join(CALLER_NAMES)})")
        if len(tok) < TOKEN_MIN or not all(0x21 <= ord(c) <= 0x7e for c in tok):
            raise RuntimeError(f"{name}: the {k} token must be >= {TOKEN_MIN} printable ASCII characters")
    return d


def _off(env, name, what: str) -> None:
    raw = (env.get(name) or "").strip().lower()
    if raw not in ("", "none", "0"):
        raise RuntimeError(f"{name}={raw!r}: {what} is not built in this service; leave it unset (the fail-closed "
                           "stand-in answers 'not delivered' / 'unavailable')")


def load(env: Optional[dict] = None) -> Settings:
    env = dict(os.environ) if env is None else env
    token = env.get("LEGAL_SERVICE_TOKEN")
    if not token:
        raise RuntimeError("LEGAL_SERVICE_TOKEN is not set. legal-py refuses to start without an auth token "
                           "(fail closed, not open).")
    andre = env.get("LEGAL_ANDRE_APPROVAL_TOKEN") or None
    callers = _tokens(env, "LEGAL_CALLER_TOKENS")
    every = list(callers.values())
    if len(set(every)) != len(every):
        raise RuntimeError("LEGAL_CALLER_TOKENS: every token must be distinct")
    if token in every or (andre and andre in every):
        raise RuntimeError("a caller token equals the service or Andre token")
    _off(env, "LEGAL_COUNSEL_CHANNEL", "a counsel channel (spec D1: engagement letter TBD)")
    _off(env, "LEGAL_ESIGN_PROVIDER", "an e-sign provider (spec D2, LR decision 7)")
    if _flag(env, "LEGAL_PORTAL_FAQ", False):
        raise RuntimeError("LEGAL_PORTAL_FAQ=1: portal FAQ answers are not built (spec D5, CQ-15: route only); "
                           "refusing to start")
    unpinned = _flag(env, "LEGAL_ALLOW_UNPINNED_SEED", False)
    seed_sha = env.get("LEGAL_SEED_SHA256") or None
    if seed_sha is not None and seed_sha != PINNED_SEED_SHA256 and not unpinned:
        raise RuntimeError("LEGAL_SEED_SHA256 differs from the pinned rules seed hash; refusing to start "
                           "(set LEGAL_ALLOW_UNPINNED_SEED=1 for a NON-PRODUCTION run)")
    if unpinned and seed_sha is None:
        raise RuntimeError("LEGAL_ALLOW_UNPINNED_SEED=1 needs LEGAL_SEED_SHA256 (the unpinned seed's own hash, stated)")
    comp = [env.get(k) or None for k in ("LEGAL_COMPLIANCE_URL", "LEGAL_COMPLIANCE_TOKEN",
                                         "LEGAL_COMPLIANCE_CALLER_TOKEN")]
    if any(comp) and not all(comp):
        raise RuntimeError("LEGAL_COMPLIANCE_URL, LEGAL_COMPLIANCE_TOKEN and LEGAL_COMPLIANCE_CALLER_TOKEN must be "
                           "set together (or none: the fail-closed Compliance stand-in)")
    raw_thr = (env.get("LEGAL_DISPUTE_THRESHOLD") or "5000.00").strip()
    if not _MONEY.fullmatch(raw_thr) or Decimal(raw_thr) <= 0:
        raise RuntimeError('LEGAL_DISPUTE_THRESHOLD must be a positive money string like "5000.00"')
    tz = (env.get("LEGAL_BUSINESS_TZ") or "America/Los_Angeles").strip()
    try:
        from zoneinfo import ZoneInfo
        ZoneInfo(tz)
    except Exception:  # noqa: BLE001 - any failure: refuse (no silent UTC fallback)
        raise RuntimeError(f"LEGAL_BUSINESS_TZ={tz!r} is not a known IANA time zone on this host") from None
    return Settings(
        service_token=token, caller_tokens=callers, andre_token=andre,
        seed_dir=env.get("LEGAL_SEED_DIR") or SEED_DIR, seed_sha256=seed_sha, allow_unpinned_seed=unpinned,
        data_dir=env.get("LEGAL_DATA_DIR") or None,
        ledger_url=env.get("LEDGER_SERVICE_URL") or None, ledger_token=env.get("LEDGER_SERVICE_TOKEN") or None,
        reconcile_mode=_flag(env, "LEGAL_RECONCILE_MODE", False),
        compliance_url=comp[0], compliance_token=comp[1], compliance_caller_token=comp[2],
        agent_max_fallback=_int(env, "LEGAL_AGENT_MAX_FALLBACK", 1, 0, 1),
        dispute_threshold=Decimal(raw_thr),
        memo_review_days=_int(env, "LEGAL_MEMO_REVIEW_DAYS", 90, 1, 90),
        hold_renotice_days=_int(env, "LEGAL_HOLD_RENOTICE_DAYS", 90, 1, 90),
        filing_alert_days=_int(env, "LEGAL_FILING_ALERT_DAYS", 60, 1, 365),
        esign_consent_required=_flag(env, "LEGAL_ESIGN_CONSENT_REQUIRED", True),
        business_tz=tz,
    )


def read_seeds(settings: Settings) -> dict[str, bytes]:
    """Every seed file's bytes, checked against its pin (the rules seed against the stated override)."""
    out = {}
    for name, pin in PINNED_SEEDS.items():
        path = os.path.join(settings.seed_dir, name)
        with open(path, "rb") as fh:
            out[name] = fh.read()
        import hashlib
        got = hashlib.sha256(out[name]).hexdigest()
        if name == RULES_SEED:
            want = settings.seed_sha256 if (settings.allow_unpinned_seed and settings.seed_sha256) else pin
        else:
            want = pin
        if got != want:
            raise RuntimeError(f"seed {name} SHA-256 {got} does not match the expected {want}; refusing to start "
                               "(the seed must be the generated file, unchanged)")
    return out
