"""The closed catalogue of reason codes Cybersecurity (22) answers with. An error body carries one of these and
nothing from the request (no value, no token, no caller text). ``R(code)`` refuses a code not listed here."""

from __future__ import annotations

CODES = frozenset({
    # vault
    "SECRET_NOT_FOUND", "SECRET_EXISTS", "SECRET_DESTROYED", "SECRET_FROZEN", "NOT_A_READER", "PURPOSE_NOT_ALLOWED",
    "CANARY_TOUCHED", "READERS_NOT_ALLOWED", "VALUE_REQUIRED", "VALUE_NOT_ALLOWED", "VALUE_ENCODING",
    "PRESERVATION_HOLD", "VAULT_UNAVAILABLE", "SEAL_BROKEN", "RELEASE_RATE_EXCEEDED", "NOT_OWNER",
    # callers, freezes, lockdown
    "CALLER_UNKNOWN", "CALLER_NOT_ALLOWED", "CALLER_FROZEN", "LOCKDOWN", "FREEZE_NOT_FOUND", "FREEZE_LIFTED",
    "FREEZE_TARGET", "AUDIENCE_REFUSED",
    # approvals and passkeys
    "APPROVAL_REQUIRED", "APPROVAL_CHALLENGE_UNKNOWN", "APPROVAL_CHALLENGE_EXPIRED", "APPROVAL_CHALLENGE_USED",
    "APPROVAL_ACTION_MISMATCH", "APPROVAL_CREDENTIAL_UNKNOWN", "PASSKEYS_NOT_CONFIGURED", "ENROLL_TOKEN_REFUSED",
    "ENROLL_NEEDS_APPROVAL", "PASSKEY_ALREADY_ENROLLED", "LAST_PASSKEY", "PASSKEY_NOT_FOUND",
    # holds, incidents, findings
    "HOLD_NOT_FOUND", "HOLD_RELEASED", "INCIDENT_NOT_FOUND", "INCIDENT_CLOSED", "FINDING_NOT_FOUND",
    "FINDING_NOT_OPEN", "ACCEPTANCE_TOO_LONG",
    # generic
    "REQUEST_ID_REUSED", "LEDGER_UNAVAILABLE", "STORE_UNAVAILABLE", "INTEGRITY_UNVERIFIED", "JOB_UNKNOWN",
    "INVALID",
    # webauthn.WebAuthnError codes
    "PASSKEY_BAD_CLIENT_DATA", "PASSKEY_BAD_CHALLENGE", "PASSKEY_BAD_AUTH_DATA", "PASSKEY_BAD_SIGNATURE",
    "PASSKEY_BAD_ATTESTATION", "PASSKEY_BAD_PUBLIC_KEY", "PASSKEY_WRONG_CEREMONY", "PASSKEY_CHALLENGE_MISMATCH",
    "PASSKEY_ORIGIN_REFUSED", "PASSKEY_CROSS_ORIGIN_REFUSED", "PASSKEY_RP_MISMATCH", "PASSKEY_USER_NOT_PRESENT",
    "PASSKEY_USER_NOT_VERIFIED", "PASSKEY_ALGORITHM_REFUSED", "PASSKEY_ATTESTATION_FORMAT_REFUSED",
    "PASSKEY_SIGNATURE_INVALID", "PASSKEY_COUNTER_REGRESSION", "PASSKEY_NOT_CONFIGURED", "PASSKEY_SUSPENDED",
})


def R(code: str) -> str:
    if code not in CODES:
        raise AssertionError(f"reason code not in the catalogue: {code}")
    return code
