"""The closed catalogue of reason codes New Business Development answers with. An error body carries one of these and
nothing from the request (no email, no name, no text). ``R(code)`` refuses a code not listed here."""

from __future__ import annotations

CODES = frozenset({
    # callers and Andre
    "CALLER_UNKNOWN", "CALLER_NOT_ALLOWED", "ANDRE_APPROVAL_REQUIRED", "ANDRE_APPROVAL_INVALID", "ANDRE_NOT_CONFIGURED",
    # pursuits
    "PURSUIT_NOT_FOUND", "PURSUIT_EXISTS", "PURSUIT_CLOSED", "STAGE_NOT_ALLOWED", "DEADLINE_REQUIRED",
    "DEADLINE_PASSED", "QUALIFICATION_REQUIRED", "QUALIFICATION_STALE", "BID_DECISION_REQUIRED", "COUNTERPARTY_INVALID", "VALUE_INVALID",
    "DEAL_APPROVAL_REQUIRED", "DEAL_APPROVAL_STALE", "DEAL_APPROVAL_NOT_NEEDED", "SOURCE_NOT_WIRED",
    "NOT_A_GOVERNMENT_BID", "CHECKLIST_CODE_UNKNOWN", "CHECKLIST_LABEL_REQUIRED", "CHECKLIST_LABEL_REFUSED",
    "CHECKLIST_TOO_LARGE", "CHECKLIST_ITEM_NOT_FOUND", "CHECKLIST_HASH_MISMATCH", "CHECKLIST_ALREADY_ATTESTED",
    "CHECKLIST_INCOMPLETE", "LOSS_REASON_REQUIRED",
    # boilerplate and responses
    "BLOCK_NOT_FOUND", "BLOCK_EXISTS", "BLOCK_NOT_APPROVED", "BLOCK_HASH_MISMATCH", "BLOCK_BRAND_MISMATCH",
    "BLOCK_ALREADY_APPROVED", "RESPONSE_NOT_FOUND", "RESPONSE_EXISTS", "RESPONSE_EMPTY", "RESPONSE_TOO_LARGE", "RESPONSE_NOT_DRAFT",
    "RESPONSE_NOT_APPROVED", "RESPONSE_HASH_MISMATCH", "RESPONSE_SUPERSEDED", "RESPONSE_ALREADY_QUEUED",
    "FLAGS_NOT_ACKNOWLEDGED", "SUBMISSION_NOT_FOUND", "SUBMISSION_NOT_QUEUED", "SUBMISSION_NOT_SENDING", "STATE_HASH_MISMATCH",
    "PAYOUT_NOT_STUCK",
    # partners, deals and commissions
    "PARTNER_NOT_FOUND", "PARTNER_EXISTS", "PARTNER_KIND_INVALID", "PARTNER_BRAND_MISMATCH", "RATE_INVALID", "RATE_NOT_APPROVED",
    "RATE_VERSION_STALE", "RATE_ALREADY_APPROVED", "TAX_REF_INVALID", "PAYEE_REF_INVALID", "TAX_ID_RAW_REFUSED", "PAYEE_NOT_READY",
    "DEAL_NOT_FOUND", "DEAL_CLOSED", "DEAL_NOT_WON", "MONEY_INVALID", "CURRENCY_NOT_SUPPORTED",
    "FINANCE_EVENT_REUSED", "PAYOUT_NOT_FOUND", "PAYOUT_NOT_WITH_FINANCE", "AGREEMENT_KIND_INVALID",
    "LEGAL_UNAVAILABLE", "AGREEMENT_NOT_IN_FORCE",
    # outreach
    "CONTACT_NOT_FOUND", "CONTACT_EXISTS", "EMAIL_INVALID", "SUPPRESSED", "CONTACT_HELD", "HOLD_NOT_FOUND",
    "HOLD_CLOSED", "OUTREACH_NOT_CONFIGURED", "TEMPLATE_NOT_FOUND", "TEMPLATE_EXISTS", "TEMPLATE_NOT_APPROVED",
    "TEMPLATE_HASH_MISMATCH", "TEMPLATE_ALREADY_APPROVED", "TEMPLATE_BRAND_MISMATCH", "MERGE_FIELD_REFUSED",
    "URL_NOT_APPROVED", "SUBJECT_DECEPTIVE", "PLACEHOLDER_UNKNOWN", "UNSUBSCRIBE_TOKEN_UNKNOWN",
    "REPLY_SENDER_REQUIRED", "MESSAGE_NOT_FOUND", "MESSAGE_NOT_QUEUED", "MESSAGE_NOT_SENT", "QUEUE_FULL",
    # hand-offs and tasks
    "TASK_NOT_FOUND", "TASK_CLOSED",
    # generic
    "REQUEST_ID_REUSED", "LEDGER_UNAVAILABLE", "STORE_UNAVAILABLE", "INTEGRITY_UNVERIFIED", "SERVICE_CLOSED",
    "JOB_UNKNOWN", "JOB_RUNNING", "INVALID", "FORBIDDEN_FIELD",
})


def R(code: str) -> str:
    if code not in CODES:
        raise AssertionError(f"reason code not in the catalogue: {code}")
    return code
