"""The closed catalogue of reason codes the Client Fix lane answers with. An error body carries one of these and nothing
from the request (no store data, no token, no text). ``R(code)`` refuses a code not listed here."""

from __future__ import annotations

CODES = frozenset({
    # callers, Andre and the client
    "CALLER_UNKNOWN", "CALLER_NOT_ALLOWED", "ANDRE_APPROVAL_REQUIRED", "ANDRE_APPROVAL_INVALID", "ANDRE_NOT_CONFIGURED",
    "CLIENT_SESSION_REQUIRED", "CLIENT_SESSION_INVALID", "CLIENT_SESSION_EXPIRED", "CLIENT_MISMATCH",
    # connections
    "CONNECTION_NOT_FOUND", "CONNECTION_EXISTS", "CONNECTION_REVOKED", "CONNECTOR_UNKNOWN", "CONNECTOR_NOT_BUILT",
    "CONNECTOR_NOT_WIRED", "CONNECTOR_GATED", "ACCOUNT_REF_INVALID", "ACCOUNT_BOUND_ELSEWHERE", "TOKEN_REF_INVALID",
    "TOKEN_REF_IN_USE", "SCOPES_INSUFFICIENT", "SECRET_REFUSED",
    # findings and jobs
    "FINDING_NOT_FOUND", "FINDING_EXISTS", "FINDING_NOT_OPEN", "CHECK_UNKNOWN", "CHECK_CONNECTOR_MISMATCH",
    "JOB_NOT_FOUND", "JOB_STATE", "JOB_EMPTY", "JOB_TOO_LARGE", "ITEM_NOT_FOUND", "ITEM_STATE",
    "QUOTE_HASH_MISMATCH", "QUOTE_NOT_ACCEPTED", "PAYMENT_REQUIRED", "PAYMENT_MISMATCH", "FINANCE_EVENT_REUSED",
    "MONEY_INVALID", "CURRENCY_NOT_SUPPORTED",
    # plans, approval, apply
    "PLAN_REQUIRED", "PLAN_INCOMPLETE", "PLAN_HASH_MISMATCH", "APPROVAL_REQUIRED", "APPROVAL_STALE",
    "OP_NOT_ALLOWED", "OP_FIELD_NOT_ALLOWED", "OP_TARGET_INVALID", "OP_VALUE_INVALID", "OP_DUPLICATE_KEY",
    "OP_NO_CHANGE", "OPS_TOO_MANY", "TENANT_MISMATCH", "RESOURCE_LEASED", "RESOURCE_FROZEN", "APPLY_IN_PROGRESS",
    "LEASE_NOT_FOUND", "LEASE_NOT_ACTIVE", "STATE_HASH_MISMATCH", "MODEL_NOT_WIRED", "NOT_FROZEN",
    "MANUAL_NOT_PENDING", "RESOURCE_MISMATCH", "ENGINEERS_FAILED", "OP_NOT_FOR_CHECK", "REDIRECT_CHAIN", "STATE_UNREADABLE",
    # refunds
    "REFUND_NOT_FOUND", "REFUND_STATE", "REFUND_HASH_MISMATCH", "REFUND_NOT_DUE",
    # tasks
    "TASK_NOT_FOUND", "TASK_CLOSED",
    # generic
    "REQUEST_ID_REUSED", "REQUEST_IN_PROGRESS", "LEDGER_UNAVAILABLE", "STORE_UNAVAILABLE", "INTEGRITY_UNVERIFIED",
    "SERVICE_CLOSED", "JOB_UNKNOWN", "JOB_RUNNING", "INVALID", "FORBIDDEN_FIELD",
})


def R(code: str) -> str:
    if code not in CODES:
        raise AssertionError(f"reason code not in the catalogue: {code}")
    return code
