"""
Environment configuration (Finance spec §0.2, §D, §G). Every rule fails closed: a configuration the service cannot
honor refuses start-up with a plain message. Every option that would need something this build does not have (a
wired rail, bank, tax agent, vault, GL, Clipper Network / Legal / People / push client, direct ACH, card
prepayments, late fees, a refund fee, a reserve, rail reversals, a custody model other than ZBC's own deposit)
refuses to start rather than pretend.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Optional

import money

CALLER_NAMES = ("compliance_38", "clipper_network", "verification_integrity", "creative_production", "onboarding",
                "legal_37", "scheduler", "rail_gateway", "bank_feed")
TOKEN_MIN = 32
# SHA-256 of seed/fin_rules_seed.json as generated by devtools/gen_rules_seed.py (pinned in ADR 0009).
PINNED_SEED_SHA256 = "617567883f3222949e8577cbd23eed7414e5e90e9fd8ac87a2ec95b0695bc7d4"
DEFAULT_SEED_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "seed", "fin_rules_seed.json")
WEEKDAYS = ("MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN")
RAILS = ("stripe", "trolley")


@dataclass
class Settings:
    service_token: str
    caller_tokens: dict = field(default_factory=dict)
    andre_token: Optional[str] = None
    second_approver_token: Optional[str] = None
    dual_human_threshold: Decimal = Decimal("0.00")
    seed_path: str = DEFAULT_SEED_PATH
    seed_sha256: Optional[str] = None
    allow_unpinned_seed: bool = False
    data_dir: Optional[str] = None
    ledger_url: Optional[str] = None
    ledger_token: Optional[str] = None
    reconcile_mode: bool = False
    vi_url: Optional[str] = None
    vi_token: Optional[str] = None
    vi_caller_token: Optional[str] = None
    compliance_url: Optional[str] = None
    compliance_token: Optional[str] = None
    compliance_caller_token: Optional[str] = None
    rails: tuple = RAILS
    run_weekday: str = "FRI"
    run_local_time: str = "10:00"
    recon_local_time: str = "07:00"
    min_payout: Decimal = Decimal("10.00")
    final_payout_min: Decimal = Decimal("0.01")
    unmatched_tin_policy: str = "block"
    ofac_max_age_days: int = 1
    threshold_1099: dict = field(default_factory=lambda: {2026: Decimal("2000.00")})
    close_workdays: int = 5
    release_delay_h: int = 12
    approval_ttl_h: int = 48
    cooling_off_h: int = 72
    limit_payee_run: Decimal = Decimal("2500.00")
    limit_payee_30d: Decimal = Decimal("10000.00")
    limit_first_payout: Decimal = Decimal("500.00")
    limit_batch_net: Decimal = Decimal("50000.00")
    limit_batch_items: int = 500
    clawback_writeoff_min_days: int = 180
    restricted_buffer: Decimal = Decimal("0.00")
    access_review_days: int = 90
    evidence_retention_days: int = 2557


def _int(env, name, default, lo, hi) -> int:
    raw = env.get(name)
    if raw in (None, ""):
        return default
    try:
        v = int(raw)
    except ValueError:
        v = lo - 1
    if not lo <= v <= hi:
        raise RuntimeError(f"{name} must be an integer {lo}..{hi}")
    return v


def _money(env, name, default: str, positive: bool = False) -> Decimal:
    raw = env.get(name)
    if raw in (None, ""):
        return Decimal(default)
    try:
        return money.parse(raw.strip(), positive=positive)
    except money.MoneyError:
        raise RuntimeError(f"{name} must be a two-decimal money string like \"10.00\"") from None


def _flag(env, name, default: bool) -> bool:
    raw = (env.get(name) or "").strip()
    if raw == "":
        return default
    if raw not in ("0", "1"):
        raise RuntimeError(f"{name} must be 0 or 1")
    return raw == "1"


def _only(env, name, allowed: tuple, default: str, why: str) -> str:
    raw = (env.get(name) or "").strip().lower() or default
    if raw not in allowed:
        raise RuntimeError(f"{name}={raw!r}: only {', '.join(allowed)} is built ({why}); refusing to start")
    return raw


def _off(env, name, what: str) -> None:
    raw = (env.get(name) or "").strip().lower()
    if raw not in ("", "none", "0"):
        raise RuntimeError(f"{name}={raw[:40]!r}: {what} is not built in this service; leave it unset (the fail-closed "
                           "stand-in answers 'unavailable')")


def _tokens(env, name) -> dict:
    raw = env.get(name)
    if not raw:
        return {}
    try:
        d = json.loads(raw)
    except ValueError:
        d = None
    if not isinstance(d, dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in d.items()):
        raise RuntimeError(f'{name} must be a JSON object {{"name": "token", ...}}')
    for k, tok in d.items():
        if k not in CALLER_NAMES:
            raise RuntimeError(f"{name}: unknown caller name (allowed: {', '.join(CALLER_NAMES)})")
        if len(tok) < TOKEN_MIN or not all(0x21 <= ord(c) <= 0x7e for c in tok):
            raise RuntimeError(f"{name}: the {k} token must be >= {TOKEN_MIN} printable ASCII characters")
    return d


def _thin(env, prefix: str, what: str) -> list:
    vals = [env.get(f"{prefix}_{k}") or None for k in ("URL", "TOKEN", "CALLER_TOKEN")]
    if any(vals) and not all(vals):
        raise RuntimeError(f"{prefix}_URL, {prefix}_TOKEN and {prefix}_CALLER_TOKEN must be set together (or none: "
                           f"the fail-closed {what} stand-in)")
    return vals


def load(env: Optional[dict] = None) -> Settings:
    env = dict(os.environ) if env is None else env
    token = env.get("FIN_SERVICE_TOKEN")
    if not token:
        raise RuntimeError("FIN_SERVICE_TOKEN is not set. finance-py refuses to start without an auth token "
                           "(fail closed, not open).")
    if len(token) < TOKEN_MIN or not all(0x21 <= ord(c) <= 0x7e for c in token):
        raise RuntimeError(f"FIN_SERVICE_TOKEN must be >= {TOKEN_MIN} printable ASCII characters")
    andre = env.get("FIN_ANDRE_APPROVAL_TOKEN") or None
    second = env.get("FIN_SECOND_APPROVER_TOKEN") or None
    callers = _tokens(env, "FIN_CALLER_TOKENS")
    every = list(callers.values())
    if len(set(every)) != len(every):
        raise RuntimeError("FIN_CALLER_TOKENS: every caller token must be distinct")
    for t, what in ((andre, "FIN_ANDRE_APPROVAL_TOKEN"), (second, "FIN_SECOND_APPROVER_TOKEN")):
        if t is not None and (len(t) < TOKEN_MIN or not all(0x21 <= ord(c) <= 0x7e for c in t)):
            raise RuntimeError(f"{what} must be >= {TOKEN_MIN} printable ASCII characters")
    specials = [t for t in (token, andre, second) if t]
    if len(set(specials)) != len(specials) or any(t in every for t in specials):
        raise RuntimeError("the service, Andre, second-approver and caller tokens must all be distinct (spec §D)")
    # --- founder-locked model and custody (D1, FIN-CQ-01/02) ---
    _only(env, "FIN_REVENUE_MODEL", ("principal",), "principal", "spec D1: Model A, ZBC sells verified views as principal")
    _only(env, "FIN_CUSTODY_MODEL", ("own_deposit",), "own_deposit",
          "FBO / escrow agent / Stripe funds segregation need counsel memo FIN-CQ-02 and are not built")
    _only(env, "FIN_STRIPE_LOSSES", ("stripe",), "stripe", "spec D2: Stripe bears negative balances")
    raw_rails = env.get("FIN_RAILS")
    rails = RAILS if raw_rails in (None, "") else tuple(r.strip().lower() for r in raw_rails.split(",") if r.strip())
    for r in rails:
        if r not in RAILS:
            raise RuntimeError(f"FIN_RAILS: {r[:20]!r} is not built (stripe, trolley; direct ACH is not built, spec D3)")
    for name, what in (("FIN_RAIL_STRIPE", "a wired Stripe Connect adapter (credentials via the vault)"),
                       ("FIN_RAIL_TROLLEY", "a wired Trolley adapter (credentials via the vault)"),
                       ("FIN_BANK_FEED", "a bank feed / bank transfer adapter (bank not chosen)"),
                       ("FIN_TAX_AGENT", "a tax agent adapter (TIN matching route, FIN-CQ-06)"),
                       ("FIN_VAULT", "the Cybersecurity 22 vault"),
                       ("FIN_CN_URL", "a Clipper Network thin client"), ("FIN_LEGAL_URL", "a Legal 37 thin client"),
                       ("FIN_PEOPLE_URL", "a People 43 thin client"), ("FIN_PUSH_URL", "a push channel to Andre"),
                       ("FIN_IDENTITY_HMAC_KEY", "an identity HMAC key outside the vault (it lives only in the vault)")):
        _off(env, name, what)
    _only(env, "FIN_GL", ("qbo", "none"), "qbo", "the QBO adapter is a stand-in; nothing else is built")
    for name, why in (("FIN_RAIL_REVERSAL_ENABLED", "clawback is ledger netting only (D5, FIN-16)"),
                      ("FIN_CARD_PREPAYMENTS", "card acceptance waits for counsel row FIN-CQ-09 (D11)"),
                      ("FIN_LATE_FEES", "late fees wait for counsel row FIN-CQ-09 (D11)")):
        if _flag(env, name, False):
            raise RuntimeError(f"{name}=1: {why}; refusing to start")
    if _int(env, "FIN_REFUND_ADMIN_FEE_PCT", 0, 0, 100) != 0:
        raise RuntimeError("FIN_REFUND_ADMIN_FEE_PCT must be 0 (D12, Andre; FIN-CQ-04 blocks any fee)")
    if _int(env, "FIN_RESERVE_PCT", 0, 0, 100) != 0:
        raise RuntimeError("FIN_RESERVE_PCT: a rolling reserve is not built; leave it 0")
    policy = _only(env, "FIN_UNMATCHED_TIN_POLICY", ("block", "withhold_24"), "block", "spec D6")
    weekday = (env.get("FIN_RUN_WEEKDAY") or "FRI").strip().upper()
    if weekday not in WEEKDAYS:
        raise RuntimeError("FIN_RUN_WEEKDAY must be MON..SUN")
    for name, default in (("FIN_RUN_LOCAL_TIME", "10:00"), ("FIN_RECON_LOCAL_TIME", "07:00")):
        if not re.fullmatch(r"([01][0-9]|2[0-3]):[0-5][0-9]", (env.get(name) or default).strip()):
            raise RuntimeError(f"{name} must be HH:MM")
    if _int(env, "FIN_OFAC_MAX_AGE_DAYS", 1, 1, 1) != 1:
        raise RuntimeError("FIN_OFAC_MAX_AGE_DAYS must be 1")          # unreachable; kept explicit
    delay = _int(env, "FIN_RELEASE_DELAY_H", 12, 1, 168)
    ttl = _int(env, "FIN_APPROVAL_TTL_H", 48, 2, 336)
    if ttl <= delay:
        raise RuntimeError("FIN_APPROVAL_TTL_H must be greater than FIN_RELEASE_DELAY_H")
    thresholds = {2026: _money(env, "FIN_1099NEC_THRESHOLD_2026", "2000.00", positive=True)}
    for y in range(2027, 2031):
        v = env.get(f"FIN_1099NEC_THRESHOLD_{y}")
        if v:
            thresholds[y] = _money(env, f"FIN_1099NEC_THRESHOLD_{y}", "2000.00", positive=True)
    unpinned = _flag(env, "FIN_ALLOW_UNPINNED_SEED", False)
    seed_sha = env.get("FIN_SEED_SHA256") or None
    if seed_sha is not None and seed_sha != PINNED_SEED_SHA256 and not unpinned:
        raise RuntimeError("FIN_SEED_SHA256 differs from the pinned seed hash; refusing to start "
                           "(set FIN_ALLOW_UNPINNED_SEED=1 for a NON-PRODUCTION run)")
    if unpinned and seed_sha is None:
        raise RuntimeError("FIN_ALLOW_UNPINNED_SEED=1 needs FIN_SEED_SHA256 (the unpinned seed's own hash, stated)")
    vi = _thin(env, "FIN_VI", "Verification and Integrity")
    cmp_ = _thin(env, "FIN_COMPLIANCE", "Compliance (38)")
    second_threshold = _money(env, "FIN_DUAL_HUMAN_THRESHOLD", "0.00")
    return Settings(
        service_token=token, caller_tokens=callers, andre_token=andre, second_approver_token=second,
        dual_human_threshold=second_threshold,
        seed_path=env.get("FIN_SEED_PATH") or DEFAULT_SEED_PATH, seed_sha256=seed_sha, allow_unpinned_seed=unpinned,
        data_dir=env.get("FIN_DATA_DIR") or None,
        ledger_url=env.get("LEDGER_SERVICE_URL") or None, ledger_token=env.get("LEDGER_SERVICE_TOKEN") or None,
        reconcile_mode=_flag(env, "FIN_RECONCILE_MODE", False),
        vi_url=vi[0], vi_token=vi[1], vi_caller_token=vi[2],
        compliance_url=cmp_[0], compliance_token=cmp_[1], compliance_caller_token=cmp_[2],
        rails=rails, run_weekday=weekday,
        run_local_time=(env.get("FIN_RUN_LOCAL_TIME") or "10:00").strip(),
        recon_local_time=(env.get("FIN_RECON_LOCAL_TIME") or "07:00").strip(),
        min_payout=_money(env, "FIN_MIN_PAYOUT", "10.00", positive=True),
        final_payout_min=_money(env, "FIN_FINAL_PAYOUT_MIN", "0.01", positive=True),
        unmatched_tin_policy=policy, ofac_max_age_days=1, threshold_1099=thresholds,
        close_workdays=_int(env, "FIN_CLOSE_WORKDAYS", 5, 1, 10),
        release_delay_h=delay, approval_ttl_h=ttl,
        cooling_off_h=_int(env, "FIN_PAYEE_CHANGE_COOLING_OFF_H", 72, 24, 720),
        limit_payee_run=_money(env, "FIN_LIMIT_PAYEE_RUN", "2500.00", positive=True),
        limit_payee_30d=_money(env, "FIN_LIMIT_PAYEE_30D", "10000.00", positive=True),
        limit_first_payout=_money(env, "FIN_LIMIT_FIRST_PAYOUT", "500.00", positive=True),
        limit_batch_net=_money(env, "FIN_LIMIT_BATCH_NET", "50000.00", positive=True),
        limit_batch_items=_int(env, "FIN_LIMIT_BATCH_ITEMS", 500, 1, 500),
        clawback_writeoff_min_days=_int(env, "FIN_CLAWBACK_WRITEOFF_MIN_DAYS", 180, 180, 3650),
        restricted_buffer=_money(env, "FIN_RESTRICTED_BUFFER", "0.00"),
        access_review_days=_int(env, "FIN_ACCESS_REVIEW_DAYS", 90, 1, 90),
        evidence_retention_days=_int(env, "FIN_EVIDENCE_RETENTION_DAYS", 2557, 2557, 36500),
    )
