"""The closed catalogue of reason codes Influencer & Partnership Marketing answers with. An error body carries one of
these and nothing from the request (no email, no handle, no name, no text, no tax reference). ``R(code)`` refuses a
code not listed here."""

from __future__ import annotations

CODES = frozenset({
    # callers and Andre
    "CALLER_UNKNOWN", "CALLER_NOT_ALLOWED", "ANDRE_APPROVAL_REQUIRED", "ANDRE_APPROVAL_INVALID",
    "ANDRE_TOKEN_NOT_CONFIGURED",
    # what is never accepted
    "TAX_ID_REFUSED", "FORBIDDEN_FIELD",
    # influencers, intake, 18+
    "SOURCE_NOT_ALLOWED", "SOURCE_NOT_WIRED", "SOURCE_UNAVAILABLE", "MINOR_REFUSED", "AGE_ATTESTATION_REQUIRED",
    "INFLUENCER_BLOCKED", "NO_MINOR_REVIEW", "INFLUENCER_NOT_FOUND", "INFLUENCER_EXISTS", "INFLUENCER_NO_EMAIL",
    "INFLUENCER_NO_HANDLE",
    "EMAIL_INVALID", "HANDLE_INVALID", "HANDLE_PLATFORM_REPEATED", "TARGET_REQUIRED",
    # outreach: suppression, holds, templates, email, DMs
    "SUPPRESSED", "REPLY_HOLD", "HOLD_NOT_FOUND", "HOLD_NOT_ACTIVE", "REPLY_SENDER_REQUIRED", "QUEUE_FULL",
    "OUTREACH_NOT_CONFIGURED", "UNSUBSCRIBE_TOKEN_UNKNOWN", "MESSAGE_NOT_FOUND", "MESSAGE_NOT_QUEUED",
    "MESSAGE_NOT_SENT", "TEMPLATE_NOT_FOUND", "TEMPLATE_EXISTS", "TEMPLATE_NOT_APPROVED", "TEMPLATE_HASH_MISMATCH",
    "SUBJECT_DECEPTIVE", "MERGE_FIELD_REFUSED", "URL_NOT_APPROVED", "PLACEHOLDER_UNKNOWN", "DRAFT_NOT_FOUND",
    "DRAFT_NOT_PENDING", "DM_LENGTH",
    # approvals
    "CONTENT_HASH_MISMATCH", "ALREADY_APPROVED",
    # campaigns, briefs, deals, contracts, content
    "CAMPAIGN_NOT_FOUND", "CAMPAIGN_CLOSED", "PARTNER_REQUIRED", "PARTNER_NOT_ALLOWED", "BRIEF_NOT_FOUND",
    "BRIEF_NOT_APPROVED", "BRIEF_NOT_IN_CAMPAIGN", "DISCLOSURE_NOT_ALLOWED", "DEAL_NOT_FOUND", "DEAL_NOT_PENDING",
    "DEAL_NOT_APPROVED", "DEAL_NOT_CANCELLABLE", "MONEY_INVALID", "LEGAL_UNAVAILABLE", "CONTRACT_REFUSED",
    "CONTRACT_NOT_SENT", "CONTRACT_NOT_IN_FORCE", "CONTENT_NOT_FOUND", "CONTENT_NOT_PENDING", "CONTENT_NOT_APPROVED",
    "CONTENT_HIDDEN_CHARACTERS", "DISCLOSURE_MISSING", "DISCLOSURE_NOT_PROMINENT", "PLATFORM_LABEL_REQUIRED",
    "PLATFORM_NOT_IN_DEAL",
    # payees and payouts
    "TAX_PROFILE_REQUIRED", "TAX_FORM_MISMATCH", "FINANCE_UNAVAILABLE", "PAYEE_REFUSED", "PAYEE_NOT_VERIFIED",
    "PAYOUT_NOT_FOUND", "PAYOUT_OVER_DEAL", "CONTENT_NOT_IN_DEAL", "CONTENT_NOT_LIVE", "CONTENT_ALREADY_PAID",
    "CONTENT_REPEATED",
    # email confirmation, per-person payouts (AEGIS round 1)
    "CONFIRMATION_UNKNOWN", "CONFIRMATION_USED", "CONFIRMATION_EXPIRED", "CONFIRMATION_NOT_PENDING",
    "EMAIL_NOT_CONFIRMED", "PAYOUT_NOT_PENDING", "DISCLOSURE_OBSCURED",
    "APPLICATION_RATE_LIMITED", "CONFIRMATIONS_OPEN_LIMIT", "ID_LIST_MISMATCH",
    # generic
    "REQUEST_ID_REUSED", "REQUEST_IN_PROGRESS", "STATE_CHANGED", "LEDGER_UNAVAILABLE", "STORE_UNAVAILABLE",
    "INTEGRITY_UNVERIFIED", "SERVICE_CLOSED", "JOB_UNKNOWN", "JOB_RUNNING", "INVALID",
})


def R(code: str) -> str:
    if code not in CODES:
        raise AssertionError(f"reason code not in the catalogue: {code}")
    return code
